version: "3"

services:
  ngnix:
    image: nginx:latest
    networks:
      - aula
    container_name: ngnix-aula-3
    ports:
      - 8080:80

  mysql:
    image: mysql:latest
    networks:
      - aula
    container_name: mysql-aula-3
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "projetoaula"

networks:
  aula-3:
    driver: bridge